#!/bin/bash
go build -tags release -ldflags "-w -s" -o go-publisher/go-publisher
cp -r templates go-publisher
cp -r scripts go-publisher
cp start go-publisher
cp config.yaml go-publisher
mkdir go-publisher/temp
mkdir go-publisher/db && cp db/server.db go-publisher/db
# tar -zcvf go-publisher.tar.gz go-publisher && rm -rf go-publisher
