#!/bin/bash
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o go-publisher/go-publisher
#cp -r templates go-publisher/
cp -r scripts go-publisher/
mkdir go-publisher/temp/
tar -zcvf go-publisher.tar.gz go-publisher && rm -rf go-publisher
