#!/bin/bash
go build -tags release -ldflags "-w -s" -o go-publisher/go-publisher
mkdir go-publisher/templates
cp -r templates/* go-publisher/templates
cp start go-publisher
cp config.yaml go-publisher
mkdir go-publisher/temp
#mkdir go-publisher/db && cp db/server.db go-publisher/db
tar -zcf go-publisher.tar.gz go-publisher && rm -rf go-publisher
