
server:
  port: 8002

db:
  sqlite3: # 本地的sqlite数据库
    path: db/server.db  # 数据库路径
  mysql:
    host: 172.168.20.157 # 数据库地址
    port: 3306  # 数据库端口
    username: root
    password: cjxx2022
    backUpPath: /root/sql_bak/temp
    ignoreDbs: ["information_schema", "sys", "performance_schema", "mysql"]

# zap日志
zap:
  filename: logs/publisher.log
  maxsize: 1
  max-backups: 5
  max-age: 30
  compress:  true
  mode: dev
  level: info

rsa:
  privateKey: MIICWwIBAAKBgQC8kRvkuQr7eO8G6PVFT08o0AgSR5Zspy1wYcbwrZMKe17xt+og kirRlZ3aAC4RXHzajF8jnRWm5fIPEW8DxVYGziDdNeeeTpBnBNs0LjuGC5OljdpW 9EFJiHEPJwpfZyeCoO/IOLP2BdprIxEWQLz6B4CaUc9+v5EEXPx9tStQYwIDAQAB AoGAEi2zELO+GUwpTvM6YfopWXfkr05zc/oR6VmjwiQZntMR7h+a1JUCx72ywAdw aYAPEUqjCV3lbneQhF9b4nMtvcN9WjTHMfPhNKQpaPDv8wjUfDiPNACPcnnKirMJ gsr5kxJGhM+Ln1iXZl8gom7B0/P5DZz/zcWiAsefbgzBdeECQQD6HypKxsG3Blem D2aVXq1g1aCnPb+TItqlEVPCE85wbUzFT3H+YKNPsg3ih4PosnUG4cn5h1NfkT4S nHhNAuerAkEAwP+arsdyY2J+A2IA4Vsa7LoWM2DX5TvO3k7v7JzdHr7T44DuVYlr qaXFxSgE9OuyOticZa1GI/VijBax2U6iKQJANsNOEjM0RKtp01z52+hv04zScOuP H1r5Pjzt9sc5Yto7fdPoJIbqGs/kRF3hXrh78PbMrwqXEYyOZ6rEmC/zowJATsOB 4zZuTnURrFvAtDe0I0xGZy1srpbb9AoPDGdwLm3+l2g03B+7Gn8W2UFd1H6kPDPO kAhJCb/JOhbA+kiHEQJALNOid8R85DO7txwndFWEDsNEk0PAgb98iXfoIo5t4H2I JqbXKdo/epOnMCDdyoKrv+5f8F/1XpF+Umznic6Jzw==

