#!/bin/bash

# 临时文件名
tempName=$1
# 上传的文件名
uploadFileName=$2
projectName=hgsq-view

# 上传的文件路径
srcFilePath=$(pwd)/temp/$tempName
# 目标文件路径
#targetFile=/home/apps/static-view
targetFilePath=$(pwd)/project-home
currTime=$(date '+%Y%m%d%H%M%S')

#fileName=${projectName}-${nameSuffix}
tempProjectName=${projectName}-update-${tempName}

echo "源文件路径:$srcFilePath, 目标文件路径:$targetFilePath"

cd "$srcFilePath" &&
unzip "${uploadFileName}" -d .
# 判断解压后的路径是否包含dist目录,如果不包含则程序退出
if [ ! -e "${srcFilePath}/dist" ]; then
  echo "压缩包文件格式不正确或不存在dist文件夹"
  exit 1
fi

# 判断是否存在项目文件夹,存在则先备份
if [ -e "${targetFilePath}/${projectName}" ]; then
  # 备份文件路径
  bakPath="${targetFilePath}/${projectName}-bak/$(date '+%Y%m%d')"
  if [ ! -e "${bakPath}" ]; then
    mkdir -p "${bakPath}"
  fi
  # 备份文件名称
  bakName="${projectName}-${tempName}-${currTime}-bak.tar.gz"
  cd "${targetFilePath}" && tar -zcvf "${bakName}" "${projectName}" && mv "${bakName}" "${bakPath}" && echo "备份成功"
fi

cd "$srcFilePath" &&
# 如果项目目录存在则需要复制源配置文件
if [ -e "${targetFilePath}/${projectName}" ];then
  \cp "${targetFilePath}"/${projectName}/static/config.json dist/static/config.json
  if [ $? -ne 0 ]; then
    echo "打包失败"
    exit 255
  fi
fi

\mv dist "${projectName}-${tempName}" && \mv "${projectName}-${tempName}" "${targetFilePath}" &&
cd "${targetFilePath}" && \rm -rf $projectName && \mv "${projectName}-${tempName}" $projectName &&
cd "${srcFilePath}"/../ && \rm -rf "${tempName}" && echo "打包成功"
