#!/bin/bash

tempName=$1 # 临时文件名
uploadFileName=$2 # 上传的文件名
projectName=hgsq-view #项目名称
targetFilePath=/home/apps/static-view # 正式用目标地址
# targetFilePath="$(pwd)/project-home" # 测试用目标地址
isBak=false # 是否备份项目文件
isBakConfig=true # 是否备份配置文件
configPath="static/config.json" # 配置文件相对路径
srcFilePath=$(pwd)/temp/$tempName # 上传的文件路径
currTime=$(date '+%Y%m%d%H%M%S') # 当前时间

# 解压
function unZipFile() {
    cd "$srcFilePath" && unzip "${uploadFileName}" -d . >/dev/null 2>&1
    # 判断解压后的路径是否包含dist目录,如果不包含则程序退出
    if [ ! -e "${srcFilePath}/dist" ]; then
        echo "压缩包文件格式不正确或不存在dist文件夹"
        exit 1
    fi
    echo "[解压]解压成功"
}

# 备份
function bak() {
    if [ -e "${targetFilePath}/${projectName}" ]; then
        # 1.复制旧的项目文件到临时源文件目录下 2.在临时目录下进行源文件压缩 3.复制压缩好的文件到备份目录下
        bakName="${projectName}-${currTime}-bak"
        # 备份文件路径
        bakPath="${targetFilePath}/${projectName}-bak/$(date '+%Y%m%d')"
        if [ ! -e "${bakPath}" ]; then
            mkdir -p "${bakPath}"
            echo "[备份]创建临时文件夹成功"
        fi
    
        \cp -r "${targetFilePath}/${projectName}" "${srcFilePath}/${bakName}"
        echo "[备份]复制项目文件到临时目录状态:$?"
        if [ $? -ne 0 ]; then
            echo "打包失败"
            exit 1
        fi

        tar -zcf "${bakName}.tar.gz" "${bakName}"
        echo "[备份]压缩状态:$?"
        if [ $? -ne 0 ]; then
            echo "打包失败"
            exit 1
        fi

        \cp "${bakName}.tar.gz" "${bakPath}"
        echo "[备份]移动状态:$?"
        if [ $? -ne 0 ]; then
            echo "打包失败"
            exit 1
        fi
        echo "[备份]备份项目成功"
    fi
}

# 备份配置文件
function bakConfigFile(){
    # 备份配置文件
    \cp ${targetFilePath}/${projectName}/${configPath} ${srcFilePath}/dist/${configPath}
    if [ $? -ne 0 ]; then
        echo "打包失败"
        exit 1
    fi
    echo "[备份]备份配置文件成功"
}

# 替换项目文件
function replace() {
    \mv dist "${projectName}"
    if [ $? -ne 0 ]; then
        echo "打包失败"
        exit 1
    fi
    cd "${targetFilePath}" && \rm -rf $projectName && 
    \cp -r "$srcFilePath/${projectName}" $projectName
    if [ $? -ne 0 ]; then
        echo "打包失败"
        exit 1
    fi
    echo "[迁移]迁移项目成功"
}

function main(){
    # 解压上传的项目文件
    unZipFile
    # 是否需要备份项目文件
    if [ ${isBak} = true ]; then
        echo "[main]备份项目文件"
        bak
    fi

    # 如果存在项目路径,则才判断是否需要备份配置文件
    if [ -e "${targetFilePath}/${projectName}" ];then
        # 是否备份配置文件
        if [ $isBakConfig = true ];then
            echo "[main]备份项目配置文件"
            bakConfigFile
        fi
    fi
    
    # 替换项目文件
    replace
    echo "打包成功"
}

# 入口
main